package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.ItemDO;
import org.springframework.web.bind.annotation.RequestParam;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Dec 15 19:53:33 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Dec 15 19:53:33 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Dec 15 19:53:33 CST 2019
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Dec 15 19:53:33 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Dec 15 19:53:33 CST 2019
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Sun Dec 15 19:53:33 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);

    /**
     *
     * @return ItemDO
     */
    List<ItemDO> listItem();

    int increaseSales(@RequestParam(name = "id") Integer id,@RequestParam(name = "amount") Integer amount);
}